import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import {itemsService} from '@/services/api/items'

export const getStaticProps = async () => {
  const res = await itemsService.getItemsList()
  const items = JSON.parse(JSON.stringify(res.items));

  return {
    props: {
      items,
    }
  }
}

export default function Home(props: any){

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
            {props.items.map((item: { id: number, name: string, createdAt: string, updatedAt: string,}) => (
                <div className={styles.card}>{item.id}{item.name}</div>
            ))}
        </h1>
      </main>
    </div>
  )
}
