import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import {getItems} from './list'

export const getStaticProps = async () => {
  const item = await getItems()
  return {
    props: {
      item: item,
    }
  }
}

export default function Home(props: any){
  console.log("props")
  console.log(props.item)
    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
            {props.item.map((item: { id: number, name: string }) => (
                <div className={styles.card}>{item.id}  {item.name}</div>
            ))}
        </h1>
      </main>
    </div>
  )
}
