openapi: 3.0.0
paths:
  /api/shops:
    post:
      operationId: ShopsController_create
      summary: 物販を作成する
      description: 物販を作成します。カレントユーザーを物販のオーナー販売者として設定します。
      parameters:
        - &ref_0
          name: x-user-id
          in: header
          description: 認証モジュールを実装したら代わりにAuthorizationヘッダーにトークンを載せて送ってもらう予定
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShopDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopModel'
        '400':
          description: ''
      tags: &ref_1
        - Shop / 物販
    get:
      operationId: ShopsController_findAll
      summary: 物販のリストを取得する
      description: カレントユーザーが販売者として所属する物販のリストを取得します。
      parameters:
        - *ref_0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopModel'
        '400':
          description: ''
      tags: *ref_1
  /api/shops/{shopId}:
    get:
      operationId: ShopsController_findOne
      summary: 物販を取得する
      description: 物販を1つ取得します。取得できる物販はカレントユーザーが販売者として所属するものに限ります。
      parameters:
        - *ref_0
        - name: x-user-id
          required: true
          in: header
          schema:
            type: string
        - name: shopId
          required: true
          in: path
          example: 1
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopModel'
        '400':
          description: ''
      tags: *ref_1
    patch:
      operationId: ShopsController_update
      summary: 物販を更新する
      description: 物販を更新します。更新できる物販はカレントユーザーが販売者として所属するものに限ります。
      parameters:
        - *ref_0
        - name: x-user-id
          required: true
          in: header
          schema:
            type: string
        - name: shopId
          required: true
          in: path
          example: 2
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShopDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopModel'
        '400':
          description: ''
      tags: *ref_1
    delete:
      operationId: ShopsController_delete
      summary: 物販を削除する
      description: 物販を削除します。削除できる物販はカレントユーザーが販売者として所属し、かつオーナー権限を持つものに限ります。
      parameters:
        - *ref_0
        - name: x-user-id
          required: true
          in: header
          schema:
            type: string
        - name: shopId
          required: true
          in: path
          example: 1
          schema:
            type: number
      responses:
        '204':
          description: ''
        '400':
          description: ''
      tags: *ref_1
info:
  title: 物販(仮) Document
  description: 物販(仮) の API リファレンスです
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateShopDto:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 128
          example: 結束バンド
      required:
        - name
    ShopModel:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 結束バンド
      required:
        - id
        - name
    UpdateShopDto:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 128
          example: 放課後ティータイム
